import { CategoryColors } from '@/constants/Colors';
import { WordTranslations } from '@/types';

export const categories = ['VERB', 'NOUN', 'ADJECTIVE', 'PLACE', 'ADVERB', 'TIME', 'CONNECTOR', 'QUESTION', 'PRONOUN'] as const;

export type Category = typeof categories[number];

export const allWords: Record<Category, WordTranslations[]> = {
    VERB: [
        { et: 'algama', es: 'comenzar', en: 'to start', ru: 'начинать' },
        { et: 'lõppema', es: 'terminar', en: 'to finish', ru: 'заканчивать' },
        { et: 'kirjutama', es: 'escribir', en: 'to write', ru: 'писать' },
        { et: 'kuulama', es: 'escuchar', en: 'to listen', ru: 'слушать' },
        { et: 'märkima', es: 'marcar', en: 'to mark', ru: 'отмечать' },
        { et: 'lugema', es: 'leer', en: 'to read', ru: 'читать' },
        { et: 'vaatama', es: 'mirar', en: 'to watch/look', ru: 'смотреть' },
        { et: 'õppima', es: 'aprender', en: 'to learn', ru: 'учиться' },
        { et: 'joonistama', es: 'dibujar', en: 'to draw', ru: 'рисовать' },
        { et: 'mängima', es: 'jugar', en: 'to play', ru: 'играть' },
        { et: 'küsima', es: 'preguntar', en: 'to ask', ru: 'спрашивать' },
        { et: 'vastama', es: 'responder', en: 'to answer', ru: 'отвечать' },
        { et: 'rääkima', es: 'hablar', en: 'to speak', ru: 'говорить' },
        { et: 'olema', es: 'ser/estar', en: 'to be', ru: 'быть' },
        { et: 'minema', es: 'ir', en: 'to go', ru: 'идти' },
        { et: 'tulema', es: 'venir', en: 'to come', ru: 'приходить' },
        { et: 'ootama', es: 'esperar', en: 'to wait', ru: 'ждать' },
        { et: 'tõusma', es: 'levantarse/subir', en: 'to rise/get up', ru: 'вставать/подниматься' },
        { et: 'istuma', es: 'sentarse', en: 'to sit', ru: 'сидеть' },
        { et: 'saama', es: 'poder/obtener', en: 'to get/can', ru: 'получать/мочь' },
        { et: 'teadma', es: 'saber/conocer', en: 'to know', ru: 'знать' },
        { et: 'maitsema', es: 'gustar/saber a', en: 'to taste', ru: 'нравиться/иметь вкус' },
        { et: 'oskama', es: 'saber hacer/poder', en: 'to know how to/can', ru: 'уметь' },
        { et: 'jalutama', es: 'caminar/pasear', en: 'to walk', ru: 'гулять' },
        { et: 'jooma', es: 'beber', en: 'to drink', ru: 'пить' },
        { et: 'koristama', es: 'limpiar/ordenar', en: 'to clean/tidy', ru: 'убирать' },
        { et: 'magama', es: 'dormir', en: 'to sleep', ru: 'спать' },
        { et: 'pesema', es: 'lavar', en: 'to wash', ru: 'мыть' },
        { et: 'sööma', es: 'comer', en: 'to eat', ru: 'есть' },
        { et: 'tantsima', es: 'bailar', en: 'to dance', ru: 'танцевать' },
        { et: 'tegema', es: 'hacer', en: 'to do/make', ru: 'делать' },
        { et: 'lükkama', es: 'empujar', en: 'to push', ru: 'толкать' },
        { et: 'tõmbama', es: 'tirar', en: 'to pull', ru: 'тянуть' },
        { et: 'elama', es: 'vivir/residir', en: 'to live', ru: 'жить' },
        { et: 'maksma', es: 'costar', en: 'to cost', ru: 'стоить' },
        { et: 'panema', es: 'poner', en: 'to put', ru: 'класть' },
        { et: 'soovima', es: 'desear/querer', en: 'to wish/want', ru: 'желать' },
        { et: 'töötama', es: 'trabajar', en: 'to work', ru: 'работать' },
        { et: 'laulma', es: 'cantar', en: 'to sing', ru: 'петь' },
        { et: 'sõitma', es: 'ir/montar/conducir', en: 'to ride/drive', ru: 'ехать' },
        { et: 'ujuma', es: 'nadar', en: 'to swim', ru: 'плавать' },
        { et: 'käima', es: 'ir regularmente/frecuentar', en: 'to go regularly/attend', ru: 'ходить' },
    ],
    NOUN: [
        { et: 'kohvipaus', es: 'pausa de café', en: 'coffee break', ru: 'перерыв на кофе' },
        { et: 'kursus', es: 'curso', en: 'course', ru: 'курс' },
        { et: 'keel', es: 'idioma/lengua', en: 'language/tongue', ru: 'язык' },
        { et: 'aadress', es: 'dirección', en: 'address', ru: 'адрес' },
        { et: 'ruum', es: 'habitación', en: 'room', ru: 'комната' },
        { et: 'number', es: 'número', en: 'number', ru: 'номер' },
        { et: 'õpetaja', es: 'profesor/a', en: 'teacher', ru: 'учитель' },
        { et: 'nimi', es: 'nombre', en: 'name', ru: 'имя' },
        { et: 'laps', es: 'niño/hijo', en: 'child', ru: 'ребёнок' },
        { et: 'öö', es: 'noche', en: 'night', ru: 'ночь' },
        { et: 'klient', es: 'cliente', en: 'client', ru: 'клиент' },
        { et: 'vesi', es: 'agua', en: 'water', ru: 'вода' },
        { et: 'komm', es: 'caramelo/dulce', en: 'candy/sweet', ru: 'конфета' },
        { et: 'küpsis', es: 'galleta/cookie', en: 'cookie/biscuit', ru: 'печенье' },
        { et: 'ananass', es: 'ananá', en: 'pineapple', ru: 'ананас' },
        { et: 'apelsin', es: 'naranja', en: 'orange', ru: 'апельсин' },
        { et: 'tomat', es: 'tomate', en: 'tomato', ru: 'помидор' },
        { et: 'banaan', es: 'banana', en: 'banana', ru: 'банан' },
        { et: 'buss', es: 'autobús', en: 'bus', ru: 'автобус' },
        { et: 'auto', es: 'auto/coche', en: 'car', ru: 'машина' },
        { et: 'pass', es: 'pasaporte', en: 'passport', ru: 'паспорт' },
        { et: 'takso', es: 'taxi', en: 'taxi', ru: 'такси' },
        { et: 'tramm', es: 'tranvía', en: 'tram', ru: 'трамвай' },
        { et: 'jogurt', es: 'yogurt', en: 'yogurt', ru: 'йогурт' },
        { et: 'pitsa', es: 'pizza', en: 'pizza', ru: 'пицца' },
        { et: 'ballett', es: 'ballet', en: 'ballet', ru: 'балет' },
        { et: 'tee', es: 'té', en: 'tea', ru: 'чай' },
        { et: 'elekter', es: 'electricidad', en: 'electricity', ru: 'электричество' },
        { et: 'kakao', es: 'cacao', en: 'cocoa', ru: 'какао' },
        { et: 'limonaad', es: 'limonada', en: 'lemonade', ru: 'лимонад' },
        { et: 'telefon', es: 'teléfono', en: 'telephone', ru: 'телефон' },
        { et: 'televiisor', es: 'televisor/TV', en: 'television', ru: 'телевизор' },
        { et: 'mikser', es: 'batidora', en: 'mixer', ru: 'миксер' },
        { et: 'raadio', es: 'radio', en: 'radio', ru: 'радио' },
        { et: 'mootor', es: 'motor', en: 'motor', ru: 'мотор' },
        { et: 'kliima', es: 'clima', en: 'climate', ru: 'климат' },
        { et: 'melon', es: 'melón', en: 'melon', ru: 'дыня' },
        { et: 'sidrun', es: 'limón', en: 'lemon', ru: 'лимон' },
        { et: 'vitamiin', es: 'vitamina', en: 'vitamin', ru: 'витамин' },
        { et: 'professor', es: 'profesor universitario', en: 'professor', ru: 'профессор' },
        { et: 'psühholoog', es: 'psicólogo', en: 'psychologist', ru: 'психолог' },
        { et: 'sekretär', es: 'secretario/a', en: 'secretary', ru: 'секретарь' },
        { et: 'arhitekt', es: 'arquitecto', en: 'architect', ru: 'архитектор' },
        { et: 'sool', es: 'sal', en: 'salt', ru: 'соль' },
        { et: 'kilo', es: 'kilo', en: 'kilo', ru: 'кило' },
        { et: 'pipar', es: 'pimienta', en: 'pepper', ru: 'перец' },
        { et: 'ketšup', es: 'ketchup', en: 'ketchup', ru: 'кетчуп' },
        { et: 'roos', es: 'rosa', en: 'rose', ru: 'роза' },
        { et: 'vaas', es: 'jarrón', en: 'vase', ru: 'ваза' },
        { et: 'kaktus', es: 'cactus', en: 'cactus', ru: 'кактус' },
        { et: 'elevant', es: 'elefante', en: 'elephant', ru: 'слон' },
        { et: 'sebra', es: 'cebra', en: 'zebra', ru: 'зебра' },
        { et: 'tiiger', es: 'tigre', en: 'tiger', ru: 'тигр' },
        { et: 'kaamel', es: 'camello', en: 'camel', ru: 'верблюд' },
        { et: 'dinosaurus', es: 'dinosaurio', en: 'dinosaur', ru: 'динозавр' },
        { et: 'majonees', es: 'mayonesa', en: 'mayonnaise', ru: 'майонез' },
        { et: 'menüü', es: 'menú', en: 'menu', ru: 'меню' },
        { et: 'šokolaad', es: 'chocolate', en: 'chocolate', ru: 'шоколад' },
        { et: 'matemaatika', es: 'matemáticas', en: 'mathematics', ru: 'математика' },
        { et: 'füüsika', es: 'física', en: 'physics', ru: 'физика' },
        { et: 'bioloogia', es: 'biología', en: 'biology', ru: 'биология' },
        { et: 'keemia', es: 'química', en: 'chemistry', ru: 'химия' },
        { et: 'šampus', es: 'champán', en: 'champagne', ru: 'шампанское' },
        { et: 'viski', es: 'whisky', en: 'whisky', ru: 'виски' },
        { et: 'pohmel', es: 'resaca', en: 'hangover', ru: 'похмелье' },
        { et: 'vein', es: 'vino', en: 'wine', ru: 'вино' },
        { et: 'viin', es: 'vodka', en: 'vodka', ru: 'водка' },
        { et: 'kass', es: 'gato', en: 'cat', ru: 'кот' },
        { et: 'jäätis', es: 'helado', en: 'ice cream', ru: 'мороженое' },
        { et: 'värv', es: 'color', en: 'color', ru: 'цвет' },
        { et: 'jook', es: 'bebida', en: 'drink', ru: 'напиток' },
        { et: 'aedvili', es: 'verdura/hortaliza', en: 'vegetable', ru: 'овощ' },
        { et: 'puuvili', es: 'fruta', en: 'fruit', ru: 'фрукт' },
        { et: 'kook', es: 'pastel', en: 'cake', ru: 'пирог/торт' },
        { et: 'juust', es: 'queso', en: 'cheese', ru: 'сыр' },
        { et: 'kartul', es: 'papa/patata', en: 'potato', ru: 'картофель' },
        { et: 'piim', es: 'leche', en: 'milk', ru: 'молоко' },
        { et: 'sibul', es: 'cebolla', en: 'onion', ru: 'лук' },
        { et: 'porgand', es: 'zanahoria', en: 'carrot', ru: 'морковь' },
        { et: 'kala', es: 'pescado', en: 'fish', ru: 'рыба' },
        { et: 'maasikas', es: 'fresa', en: 'strawberry', ru: 'клубника' },
        { et: 'õun', es: 'manzana', en: 'apple', ru: 'яблоко' },
        { et: 'vorst', es: 'salchicha', en: 'sausage', ru: 'колбаса' },
        { et: 'liha', es: 'carne', en: 'meat', ru: 'мясо' },
        { et: 'riis', es: 'arroz', en: 'rice', ru: 'рис' },
        { et: 'mahl', es: 'jugo', en: 'juice', ru: 'сок' },
        { et: 'puder', es: 'papilla', en: 'porridge', ru: 'каша' },
        { et: 'salat', es: 'ensalada', en: 'salad', ru: 'салат' },
        { et: 'supp', es: 'sopa', en: 'soup', ru: 'суп' },
        { et: 'võileib', es: 'sándwich', en: 'sandwich', ru: 'бутерброд' },
        { et: 'leib', es: 'pan', en: 'bread', ru: 'хлеб' },
        { et: 'muna', es: 'huevo', en: 'egg', ru: 'яйцо' },
        { et: 'kohv', es: 'café', en: 'coffee', ru: 'кофе' },
        { et: 'või', es: 'manteca/mantequilla', en: 'butter', ru: 'масло' },
        { et: 'õlu', es: 'cerveza', en: 'beer', ru: 'пиво' },
        { et: 'külmkapp', es: 'heladera', en: 'refrigerator', ru: 'холодильник' },
        { et: 'sõber', es: 'amigo', en: 'friend', ru: 'друг' },
        { et: 'raamat', es: 'libro', en: 'book', ru: 'книга' },
        { et: 'ilm', es: 'clima/tiempo', en: 'weather', ru: 'погода' },
        { et: 'päike', es: 'sol', en: 'sun', ru: 'солнце' },
        { et: 'müüja', es: 'vendedor/a', en: 'seller/salesperson', ru: 'продавец' },
    ],
    ADJECTIVE: [
        { et: 'suur', es: 'grande', en: 'big', ru: 'большой' },
        { et: 'hea', es: 'bueno', en: 'good', ru: 'хороший' },
        { et: 'halb', es: 'malo', en: 'bad', ru: 'плохой' },
        { et: 'normaalne', es: 'normal', en: 'normal', ru: 'нормальный' },
        { et: 'külm', es: 'frío', en: 'cold', ru: 'холодный' },
        { et: 'positiivne', es: 'positivo', en: 'positive', ru: 'позитивный' },
        { et: 'negatiivne', es: 'negativo', en: 'negative', ru: 'негативный' },
        { et: 'pessimistlik', es: 'pesimista', en: 'pessimistic', ru: 'пессимистичный' },
        { et: 'optimistlik', es: 'optimista', en: 'optimistic', ru: 'оптимистичный' },
        { et: 'huvitav', es: 'interesante', en: 'interesting', ru: 'интересный' },
        { et: 'väsinud', es: 'cansado', en: 'tired', ru: 'уставший' },
        { et: 'must', es: 'negro/sucio', en: 'black/dirty', ru: 'чёрный/грязный' },
        { et: 'roheline', es: 'verde', en: 'green', ru: 'зелёный' },
        { et: 'valge', es: 'blanco', en: 'white', ru: 'белый' },
        { et: 'punane', es: 'rojo', en: 'red', ru: 'красный' },
        { et: 'pruun', es: 'marrón', en: 'brown', ru: 'коричневый' },
        { et: 'lilla', es: 'violeta', en: 'purple', ru: 'фиолетовый' },
        { et: 'hall', es: 'gris', en: 'gray', ru: 'серый' },
        { et: 'roosa', es: 'rosa/rosado', en: 'pink', ru: 'розовый' },
        { et: 'sinine', es: 'azul', en: 'blue', ru: 'синий' },
        { et: 'oranž', es: 'naranja', en: 'orange', ru: 'оранжевый' },
        { et: 'kollane', es: 'amarillo', en: 'yellow', ru: 'жёлтый' },
        { et: 'beež', es: 'beige', en: 'beige', ru: 'бежевый' },
        { et: 'magus', es: 'dulce', en: 'sweet', ru: 'сладкий' },
        { et: 'valmis', es: 'listo/preparado', en: 'ready', ru: 'готовый' },
        { et: 'väike', es: 'pequeño', en: 'small', ru: 'маленький' },
        { et: 'palav', es: 'caliente/caluroso', en: 'hot', ru: 'жаркий' },
        { et: 'jahe', es: 'fresco', en: 'cool', ru: 'прохладный' },
        { et: 'soe', es: 'cálido/tibio', en: 'warm', ru: 'тёплый' },
        { et: 'kallis', es: 'caro', en: 'expensive', ru: 'дорогой' },
        { et: 'odav', es: 'barato', en: 'cheap', ru: 'дешёвый' },
        { et: 'pikk', es: 'largo/alto', en: 'long/tall', ru: 'длинный/высокий' },
        { et: 'uus', es: 'nuevo', en: 'new', ru: 'новый' },
        { et: 'vana', es: 'viejo', en: 'old', ru: 'старый' },
    ],
    ADVERB: [
        { et: 'hästi', es: 'bien', en: 'well', ru: 'хорошо' },
        { et: 'halvasti', es: 'mal', en: 'badly', ru: 'плохо' },
        { et: 'normaalselt', es: 'normalmente', en: 'normally', ru: 'нормально' },
        { et: 'tavaliselt', es: 'generalmente', en: 'usually', ru: 'обычно' },
        { et: 'tihti', es: 'a menudo', en: 'often', ru: 'часто' },
        { et: 'praegu', es: 'ahora', en: 'now', ru: 'сейчас' },
        { et: 'alati', es: 'siempre', en: 'always', ru: 'всегда' },
        { et: 'kunagi', es: 'alguna vez', en: 'ever', ru: 'когда-либо' },
        { et: 'siin', es: 'aquí', en: 'here', ru: 'здесь' },
        { et: 'seal', es: 'allí', en: 'there', ru: 'там' },
        { et: 'eile', es: 'ayer', en: 'yesterday', ru: 'вчера' },
        { et: 'täna', es: 'hoy', en: 'today', ru: 'сегодня' },
        { et: 'homme', es: 'mañana', en: 'tomorrow', ru: 'завтра' },
        { et: 'varsti', es: 'pronto', en: 'soon', ru: 'скоро' },
        { et: 'kiiresti', es: 'rápido', en: 'quickly', ru: 'быстро' },
        { et: 'aeglaselt', es: 'lento', en: 'slowly', ru: 'медленно' },
        { et: 'koos', es: 'juntos', en: 'together', ru: 'вместе' },
        { et: 'üksi', es: 'solo', en: 'alone', ru: 'один' },
        { et: 'peaaegu', es: 'casi', en: 'almost', ru: 'почти' },
        { et: 'juba', es: 'ya', en: 'already', ru: 'уже' },
        { et: 'veel', es: 'más/todavía', en: 'more/still', ru: 'ещё' },
        { et: 'ainult', es: 'solo/solamente', en: 'only', ru: 'только' },
        { et: 'siis', es: 'entonces', en: 'then', ru: 'тогда' },
        { et: 'jälle', es: 'otra vez', en: 'again', ru: 'снова' },
        { et: 'just', es: 'justo/exactamente', en: 'just/exactly', ru: 'именно/точно' },
        { et: 'ilma', es: 'sin', en: 'without', ru: 'без' },
        { et: 'kui', es: 'cuánto/cuán', en: 'how much/how', ru: 'как/сколько' },
    ],
    TIME: [
        { et: 'hommik', es: '(la) mañana', en: 'morning', ru: 'утро' },
        { et: 'päev', es: 'día', en: 'day', ru: 'день' },
        { et: 'õhtu', es: 'tarde/noche', en: 'evening', ru: 'вечер' },
        { et: 'öö', es: 'noche', en: 'night', ru: 'ночь' },
        { et: 'eile', es: 'ayer', en: 'yesterday', ru: 'вчера' },
        { et: 'täna', es: 'hoy', en: 'today', ru: 'сегодня' },
        { et: 'homme', es: 'mañana', en: 'tomorrow', ru: 'завтра' },
        { et: 'kevad', es: 'primavera', en: 'spring', ru: 'весна' },
        { et: 'suvi', es: 'verano', en: 'summer', ru: 'лето' },
        { et: 'sügis', es: 'otoño', en: 'autumn', ru: 'осень' },
        { et: 'talv', es: 'invierno', en: 'winter', ru: 'зима' },
        { et: 'nädalavahetus', es: 'fin de semana', en: 'weekend', ru: 'выходные' },
        { et: 'esmaspäev', es: 'lunes', en: 'Monday', ru: 'понедельник' },
        { et: 'teisipäev', es: 'martes', en: 'Tuesday', ru: 'вторник' },
        { et: 'kolmapäev', es: 'miércoles', en: 'Wednesday', ru: 'среда' },
        { et: 'neljapäev', es: 'jueves', en: 'Thursday', ru: 'четверг' },
        { et: 'reede', es: 'viernes', en: 'Friday', ru: 'пятница' },
        { et: 'laupäev', es: 'sábado', en: 'Saturday', ru: 'суббота' },
        { et: 'pühapäev', es: 'domingo', en: 'Sunday', ru: 'воскресенье' },
        { et: 'praegu', es: 'ahora', en: 'now', ru: 'сейчас' },
        { et: 'kuu', es: 'mes', en: 'month', ru: 'месяц' },
        { et: 'nädal', es: 'semana', en: 'week', ru: 'неделя' },
        { et: 'veebruar', es: 'febrero', en: 'February', ru: 'февраль' },
        { et: 'mai', es: 'mayo', en: 'May', ru: 'май' },
        { et: 'september', es: 'septiembre', en: 'September', ru: 'сентябрь' },
        { et: 'oktoober', es: 'octubre', en: 'October', ru: 'октябрь' },
        { et: 'jaanuar', es: 'enero', en: 'January', ru: 'январь' },
        { et: 'juuli', es: 'julio', en: 'July', ru: 'июль' },
        { et: 'märts', es: 'marzo', en: 'March', ru: 'март' },
        { et: 'detsember', es: 'diciembre', en: 'December', ru: 'декабрь' },
        { et: 'aprill', es: 'abril', en: 'April', ru: 'апрель' },
        { et: 'november', es: 'noviembre', en: 'November', ru: 'ноябрь' },
        { et: 'august', es: 'agosto', en: 'August', ru: 'август' },
        { et: 'sünnipäev', es: 'cumpleaños', en: 'birthday', ru: 'день рождения' },
    ],
    CONNECTOR: [
        { et: 'ja', es: 'y', en: 'and', ru: 'и' },
        { et: 'aga', es: 'pero', en: 'but', ru: 'но' },
        { et: 'sest', es: 'porque/ya que', en: 'because', ru: 'потому что' },
        { et: 'või', es: 'o', en: 'or', ru: 'или' },
        { et: 'kui', es: 'si/cuando', en: 'if/when', ru: 'если/когда' },
        { et: 'kuigi', es: 'aunque', en: 'although', ru: 'хотя' },
        { et: 'et', es: 'que/para que', en: 'that/so that', ru: 'что/чтобы' },
        { et: 'nii', es: 'así', en: 'so/thus', ru: 'так' },
        { et: 'siis', es: 'entonces', en: 'then', ru: 'тогда' },
        { et: 'ehk', es: 'o', en: 'or', ru: 'или' },
        { et: 'vaid', es: 'pero/sino', en: 'but/only', ru: 'но/только' },
        { et: 'nagu', es: 'como', en: 'like/as', ru: 'как' },
        { et: 'samuti', es: 'también', en: 'also', ru: 'также' },
        { et: 'kuna', es: 'ya que/como', en: 'since/as', ru: 'так как' },
        { et: 'enne kui', es: 'antes de que', en: 'before', ru: 'до того как' },
        { et: 'pärast kui', es: 'después de que', en: 'after', ru: 'после того как' },
        { et: 'kuni', es: 'hasta', en: 'until', ru: 'до' },
        { et: 'samas', es: 'mientras/al mismo tiempo', en: 'at the same time', ru: 'в то же время' },
    ],
    PLACE: [
        { et: 'kool', es: 'escuela', en: 'school', ru: 'школа' },
        { et: 'pood', es: 'tienda', en: 'store/shop', ru: 'магазин' },
        { et: 'kodu', es: 'casa/hogar', en: 'home', ru: 'дом' },
        { et: 'Mustamäe', es: 'Mustamäe', en: 'Mustamäe', ru: 'Мустамяэ' },
        { et: 'Tartu', es: 'Tartu', en: 'Tartu', ru: 'Тарту' },
        { et: 'Tallinn', es: 'Tallin', en: 'Tallinn', ru: 'Таллин' },
        { et: 'Pärnu', es: 'Pärnu', en: 'Pärnu', ru: 'Пярну' },
        { et: 'Narva', es: 'Narva', en: 'Narva', ru: 'Нарва' },
        { et: 'Soome', es: 'Finlandia', en: 'Finland', ru: 'Финляндия' },
        { et: 'Venemaa', es: 'Rusia', en: 'Russia', ru: 'Россия' },
        { et: 'Saaremaa', es: 'Saaremaa', en: 'Saaremaa', ru: 'Сааремаа' },
        { et: 'Pariis', es: 'París', en: 'Paris', ru: 'Париж' },
        { et: 'Berliin', es: 'Berlín', en: 'Berlin', ru: 'Берлин' },
        { et: 'London', es: 'Londres', en: 'London', ru: 'Лондон' },
        { et: 'Helsingi', es: 'Helsinki', en: 'Helsinki', ru: 'Хельсинки' },
        { et: 'kohvik', es: 'café/cafetería', en: 'café', ru: 'кафе' },
        { et: 'rand', es: 'playa', en: 'beach', ru: 'пляж' },
        { et: 'park', es: 'parque', en: 'park', ru: 'парк' },
        { et: 'turg', es: 'mercado', en: 'market', ru: 'рынок' },
        { et: 'raamatukogu', es: 'biblioteca', en: 'library', ru: 'библиотека' },
        { et: 'restoran', es: 'restaurante', en: 'restaurant', ru: 'ресторан' },
        { et: 'pank', es: 'banco', en: 'bank', ru: 'банк' },
        { et: 'apteek', es: 'farmacia', en: 'pharmacy', ru: 'аптека' },
        { et: 'hotell', es: 'hotel', en: 'hotel', ru: 'отель' },
        { et: 'kino', es: 'cine', en: 'cinema', ru: 'кино' },
        { et: 'teater', es: 'teatro', en: 'theater', ru: 'театр' },
    ],
    QUESTION: [
        { et: 'mis', es: 'qué', en: 'what', ru: 'что' },
        { et: 'mida', es: 'qué', en: 'what (object)', ru: 'что (объект)' },
        { et: 'mille', es: 'qué', en: 'what (genitive)', ru: 'чего' },
        { et: 'milline', es: 'cuál/cómo es', en: 'which/what like', ru: 'какой' },
        { et: 'miks', es: 'por qué', en: 'why', ru: 'почему' },
        { et: 'kus', es: 'dónde', en: 'where', ru: 'где' },
        { et: 'kust', es: 'de dónde', en: 'from where', ru: 'откуда' },
        { et: 'kuhu', es: 'a dónde', en: 'where to', ru: 'куда' },
        { et: 'kelle', es: 'de quién', en: 'whose', ru: 'чей' },
        { et: 'kellel', es: 'quién tiene', en: 'who has', ru: 'у кого' },
        { et: 'kellele', es: 'a quién', en: 'to whom', ru: 'кому' },
        { et: 'keda', es: 'a quién', en: 'whom', ru: 'кого' },
        { et: 'millal', es: 'cuándo', en: 'when', ru: 'когда' },
        { et: 'kui palju', es: 'cuánto/cuánta (cantidad)', en: 'how much/how many', ru: 'сколько' },
        { et: 'kuidas', es: 'cómo', en: 'how', ru: 'как' },
        { et: 'mitu', es: 'cuántos (contable)', en: 'how many', ru: 'сколько (штук)' },
        { et: 'kas', es: 'partícula interrogativa', en: 'question particle', ru: 'ли' },
        { et: 'kellega', es: 'con quién', en: 'with whom', ru: 'с кем' },
        { et: 'kumb', es: 'cuál (de dos)', en: 'which (of two)', ru: 'который (из двух)' },
        { et: 'missugune', es: 'qué tipo/clase de', en: 'what kind of', ru: 'какой (тип)' },
    ],
    PRONOUN: [
        { et: 'mina', es: 'yo', en: 'I', ru: 'я' },
        { et: 'sina', es: 'tú', en: 'you', ru: 'ты' },
        { et: 'tema', es: 'él/ella', en: 'he/she', ru: 'он/она' },
        { et: 'meie', es: 'nosotros', en: 'we', ru: 'мы' },
        { et: 'teie', es: 'ustedes', en: 'you (plural)', ru: 'вы' },
        { et: 'nemad', es: 'ellos/ellas', en: 'they', ru: 'они' },
        { et: 'ma', es: 'yo', en: 'I', ru: 'я' },
        { et: 'sa', es: 'tú', en: 'you', ru: 'ты' },
        { et: 'ta', es: 'él/ella', en: 'he/she', ru: 'он/она' },
        { et: 'nad', es: 'ellos/ellas', en: 'they', ru: 'они' },
        { et: 'mu', es: 'mi/mío', en: 'my/mine', ru: 'мой/моя/моё' },
        { et: 'su', es: 'tu/tuyo', en: 'your/yours', ru: 'твой/твоя/твоё' },
        { et: 'oma', es: 'propio', en: 'own', ru: 'свой' },
        { et: 'mind', es: 'a mí/me', en: 'me', ru: 'меня/мне' },
        { et: 'sind', es: 'a ti/te', en: 'you', ru: 'тебя/тебе' },
        { et: 'teda', es: 'a él/ella', en: 'him/her', ru: 'его/её' },
        { et: 'meid', es: 'a nosotros/nos', en: 'us', ru: 'нас/нам' },
        { et: 'teid', es: 'a ustedes', en: 'you (plural)', ru: 'вас/вам' },
        { et: 'neid', es: 'a ellos', en: 'them', ru: 'их/им' },
        { et: 'minu', es: 'de mí/mi', en: 'of me/my', ru: 'моего/моей' },
    ],
};

export const categoryColorMap: Record<Category, string> = {
    VERB: CategoryColors.yellow,
    NOUN: CategoryColors.lightgreen,
    ADJECTIVE: CategoryColors.lightpurple,
    PLACE: CategoryColors.blue,
    ADVERB: CategoryColors.red,
    TIME: CategoryColors.lightpink,
    CONNECTOR: CategoryColors.pink,
    QUESTION: CategoryColors.green,
    PRONOUN: CategoryColors.lightblue,
};